### ISSUE TITLE
Pliki z folderu docker (docker_target, docker_utest) nie są widoczne z poziomu Dockera

### ISSUE THREAD

**Issue by Szustarol** [AGHSolarPlaneCode/ISB-UAV-BUS#2]
Pliki z folderu docker, nie są widocznie z poziomu dockera,
po uruchomieniu buildu wyświetla się komunikat o braku pliku.
Prawdopodobnie potrzebny dockerfile który podepnie te pliki  z katalogu
hosta do emulowanego środowiska dockera.

Przydałoby się również udostępnienie obrazu z dockera w repo solarowym - taka sugestia.

Folder ISB (folder wejściowy dockera od buildera) jest pusty.

**Comment by Thematiq** [comment]
Bug spowodowany prawdopodobnie przez Fedorę, Hotfix dodany na mastera.
